TICKERS = {
    'Portfolio': [
        'QQQ',
        'VOO',
        'RIO',
        'KO',
        'NKE',
        'JNJ',
        'BABA',
        'AI',
    ],
    'Prospect': [
        'AAPL',
        'MSFT',
        'TSLA',
        'GOOG',
        'BAC',
        'VZ',
        'T',
        'CVX',
        'ABBV',
        'AVGO',
        'CSCO',
        'PFE',
        'MMM',
        'O',
        'TSM',
        'V',
        'NVDA',
        'WMT',
        'AMZN',
        'HSY',
        'KER.PA',
    ],
}